# For more information about the configurations used
# in this file, please see the Travis CI documentation.
# .travis.yml
# https://docs.travis-ci.com

sudo: enabled

install:
  - sudo bash -c "add-apt-repository -ys ppa:nilarimogard/webupd8 ; add-apt-repository -ys ppa:kelleyk/emacs"
  - sudo bash -c "$(curl -LSs https://github.com/dfmgr/installer/raw/main/install.sh)"
  - sudo pkmgr init
  - pkmgr update
  - sudo dotfiles admin scripts
  - dotfiles install youtube-viewer
  - bash -c "[ -f $(command -v youtube-viewer >/dev/null 2>&1) ] && echo Installed || true"

matrix:
  include:
    - os: linux
      dist: bionic
      language: bash
      sudo: enabled

notifications:
  email:
    on_failure: never
    on_success: never
